// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4579.RobotMainTestCode;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainRightMotor;
    public static SpeedController driveTrainLeftMotor;
    public static RobotDrive driveTrainRobotDrive;
    public static AnalogChannel driveTrainUltrasonic;
    public static SpeedController elevatorMotor;
    public static AnalogChannel elevatorPot;
    public static SpeedController wristMotor;
    public static AnalogChannel wristPot;
    public static SpeedController clawMotor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainRightMotor = new Jaguar(1, 3);
	LiveWindow.addActuator("Drive Train", "Right Motor", (Jaguar) driveTrainRightMotor);
        
        driveTrainLeftMotor = new Jaguar(1, 4);
	LiveWindow.addActuator("Drive Train", "Left Motor", (Jaguar) driveTrainLeftMotor);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainLeftMotor, driveTrainRightMotor);
	
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);
        

        driveTrainUltrasonic = new AnalogChannel(1, 3);
	LiveWindow.addSensor("Drive Train", "Ultrasonic", driveTrainUltrasonic);
        
        elevatorMotor = new Victor(1, 2);
	LiveWindow.addActuator("Elevator", "Motor", (Victor) elevatorMotor);
        
        elevatorPot = new AnalogChannel(1, 6);
	LiveWindow.addSensor("Elevator", "Pot", elevatorPot);
        
        wristMotor = new Victor(1, 1);
	LiveWindow.addActuator("Wrist", "Motor", (Victor) wristMotor);
        
        wristPot = new AnalogChannel(1, 2);
	LiveWindow.addSensor("Wrist", "Pot", wristPot);
        
        clawMotor = new Victor(1, 5);
	LiveWindow.addActuator("Claw", "Motor", (Victor) clawMotor);
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
