// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4579.RecycleRush3.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Auto1 extends CommandGroup {
    
    public  Auto1() {
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
    	
    	
    	/*
    	 * SKETCH OF THIS AUTONOMOUS COMMAND:
    	 * THIS AUTONOMOUS COMMAND SHOULD ONLY PICK UP THE BUCKET AND DRIVE TO THE AUTOZONE
    	 * 
    	 * STEPS:
    	 * 
    	 * 1. INJECT THE BUCKET TO ENSURE THAT IT IS CAPTURED (SPIN FOR ONLY ~1 SECOND)
    	 * 
    	 * WE DO NOT NEED TO SPIN THE BUCKET SINCE THE BUCKET WILL BE PLACED THE SAME WAY EACH TIME
    	 * 
    	 * 2. LIFT THE CONTAINER
    	 * 
    	 * PROBLEM: FROM HERE, IF WE SPIN LEFT, WE MIGHT HIT THE WALL; WE NEED TO MOVE FORWARD
    	 * 			BUT, IF WE MOVE FORWARD, WE WILL BE PUSHING THE TOTE POSSIBLY SCREWING WITH ANOTHER TEAM'S AUTO
    	 * 			WE CAN MOVE FORWARD AND ROTATE SIMULTANEOUSLY IN ONE COMMAND, BUT I THINK THAT WOULD 
    	 * 			REQUIRE SUBSYSTEM COMPLEXITY
    	 * 
    	 * NOTE: I DREW A SKETCH OF THE ROBOT AND ITS BACK RIGHT BUMPER'S PIVOT; IT BARELY EXTENDED PAST THE ROBOT, WE'LL SEE BUT IT MIGHT NOT BE A PROBLEM
    	 * 
    	 * 3. SPIN 45
    	 * 
    	 * 4. MOVE 9' TO AUTOZONE
    	 * 
    	 */
    	
    	addSequential(new Capture());
    	addSequential(new LiftContainer());
    	addSequential(new Rotate45());
    	addSequential(new DriveToAZ());
    	
    }
}
