// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4579.RecycleRush3.subsystems;

import org.usfirst.frc4579.RecycleRush3.RobotMap;
import org.usfirst.frc4579.RecycleRush3.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Aligner extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController leftMotor = RobotMap.alignerLeftMotor;
    SpeedController rightMotor = RobotMap.alignerRightMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public double alignSpeed = 1;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void leftIn() {
    	leftMotor.set(alignSpeed); // ASSUMES POSITIVE SPEED ROTATES TOWARDS THE ROBOT
    }
    
    public void rightIn() {
    	rightMotor.set(-alignSpeed); // ASSUMES NEGATIVE SPEED ROTATES TOWARDS THE ROBOT
    }
    
    public void leftOut() {
    	leftMotor.set(-alignSpeed); // ASSUMES NEGATIVE SPEED ROTATES AWAY FROM THE ROBOT
    }
    
    public void rightOut() {
    	rightMotor.set(alignSpeed); // ASSUMES POSITIVE SPEED ROTATES AWAY FROM THE ROBOT
    }
    
    public void stop() { // STOPS BOTH MOTORS
    	leftMotor.set(0);
    	rightMotor.set(0);
    }
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

