// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4579.RecycleRush4.subsystems;

import org.usfirst.frc4579.RecycleRush4.RobotMap;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class SuckWheels extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController left = RobotMap.suckWheelsLeft;
    SpeedController right = RobotMap.suckWheelsRight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    private double speed = 0.5; // Default speed of the motors in the subsystem methods (defaulted to 0.5)   

    public void leftIn() { // Sets the left wheel to spin inwards
    	left.set(speed);
    }
    
    public void rightIn() { // Sets the right wheel to spin inwards
    	right.set(speed);
    }
    
    public void leftOut() { // Sets the left wheel to spin outwards
    	left.set(-speed);
    }
    
    public void rightOut() { // Sets the right wheel to spin outwards
    	right.set(-speed);
    }
    
    public void setSpeed(double newSpeed) { // Sets the default speed of the motors in the subsystem methods
    	speed = newSpeed;
    }
    
    public double getSpeed() { // Returns the default speed of the motors in the subsystem methods
    	return speed;
    }
    
    public void stop() { // Hard stops all motors
    	left.set(0);
    	right.set(0);
    }
    
    // We do not need a default command for the suckwheels due to the subsystem's simplicity
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    }
}

